# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Oporto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'RNFirebase', path: '../node_modules/react-native-firebase/ios'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  # pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  # pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
	pod 'React', :path => '../node_modules/react-native', :subspecs => [
	  'DevSupport',
	  'BatchedBridge', # Required For React Native 0.45.0+
	  'Core',
	  # Add any other subspecs you want to use in your project
  ]
  
  # Pods for Oporto
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # target 'Oporto-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  #   # pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  #   # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  # end

  target 'OportoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end