rules:
  property-sort-order: 0
  no-ids: 0
  no-url-domains: 0
  no-url-protocols: 0
  nesting-depth:
    - 1
    -
      max-depth: 8
  no-important: 0
  no-duplicate-properties:
    - 1
    -
      exclude:
        - background-image
        - transition
        - outline
  no-misspelled-properties:
      - 1
      -
          extra-properties:
              - weight
              - overflow-scrolling
              - family
              - style
  mixins-before-declarations: 0
  no-vendor-prefixes: 0
  indentation:
    - 1
    -
      size: 'tab'
  clean-import-paths:
    - 0
  class-name-format:
    - 0
  pseudo-element:
    - 0
  force-pseudo-nesting:
    - 0
  empty-args:
    - 0
  leading-zero:
    - 0
  no-color-literals:
    - allow-rgba: true
