# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Oporto.xcodeproj")
    build_app(workspace: "Oporto.xcworkspace", scheme: "Oporto")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end

lane :beta do
  # get_certificates           # invokes cert
  # get_provisioning_profile   # invokes sigh
  # build_app(scheme: "Oporto",
  #           workspace: "Oporto.xcworkspace",
  #           include_bitcode: true)
  upload_to_testflight
end

lane :increment_build_number do
  increment_build_number(
    xcodeproj: "Oporto.xcodeproj"
  )
end 
