rules:
  property-sort-order: 0
  nesting-depth:
    - 1
    -
      max-depth: 6
  no-duplicate-properties:
    - 1
    -
      exclude:
        - background-image
  mixins-before-declarations: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  indentation:
    - 1
    -
      size: 'tab'
  clean-import-paths:
    - 0
  no-ids:
    - 0
  no-misspelled-properties:
    - 1
    -
      'extra-properties':
        - 'overflow-scrolling'
  class-name-format:
    - 1
    -
      ignore: ['select2-selection__rendered', 'select2-container--focus', 'select2-selection__arrow', 'select2-results__options', 'select2-results__option', 'select2-results__option--highlighted', 'select2-search__field', 'select2-selection__choice', 'select2-selection__choice__remove', 'paginatedThumbnails_1sxciui', 'footerCount_lkhc9u', 'Board', 'Executives']
files:
  ignore:
    - 'theme-src/css/vendor/**'
